import "@/app/styles/globals.css";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { DirectionProvider } from "@/components/ui/direction";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "@/lib/cart-context";
import localFont from "next/font/local"
export const metadata = {
  title: "فروشگاه اینترنتی",
  description: "Generated by create next app",
};

const vazirFont = localFont({
  src : [
    {
      path : "./fonts/vazirMatn/Vazirmatn-Light.woff2",
      weight : "300",
      style : "normal"
    },
    {
      path : "./fonts/vazirMatn/Vazirmatn-Medium.woff2",
      weight : "500",
      style : "normal"
    },
    {
      path : "./fonts/vazirMatn/Vazirmatn-Bold.woff2",
      weight : "700",
      style : "normal"
    },
    {
      path : "./fonts/vazirMatn/Vazirmatn-ExtraLight.woff2",
      weight : "200",
      style : "normal"
    },
  ],
  variable : "--font-vazir-matn",
  display : "swap"
})

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={vazirFont.variable}>
      <body>
        
        <DirectionProvider direction="rtl">
          <CartProvider>
            
            <main className="">
            {children}
            </main>
            
            </CartProvider>
          <Toaster />
        </DirectionProvider>
      </body>
    </html>
  );
}
